import type { Metadata } from "next";
import LegalPage, { type LegalSection } from "../LegalPage";

export const metadata: Metadata = {
  title: "Terms of Use | Subra AI",
  description: "Terms governing use of the Subra AI offline, on-device AI chat application.",
  alternates: { canonical: "/subra-ai/terms" },
  openGraph: { title: "Terms of Use | Subra AI", description: "Terms for using the Subra AI offline chat app.", url: "/subra-ai/terms", type: "website" },
};

const sections: LegalSection[] = [
  { id: "acceptance", title: "Acceptance and eligibility", content: <><p>These Terms of Use form an agreement between you and <strong>Subrata Kumar Das</strong>, the developer and operator of Subra AI (the “Developer,” “we,” “us,” or “our”). By downloading, installing, or using the app, you agree to these Terms and the Subra AI Privacy Policy. If you do not agree, do not use the app.</p><p>You must be legally capable of accepting these Terms. Subra AI is not directed to children under 13 or the minimum digital-consent age where they live. A minor may use the app only with permission and supervision from a parent or legal guardian where required by law.</p></> },
  { id: "service", title: "What Subra AI provides", content: <><p>Subra AI provides general-purpose chat and image-analysis features powered by an on-device model. The current version uses Gemma 4 through Google LiteRT/LiteRT-LM. A future version may use Google ML Kit or other on-device technology, with corresponding notices updated as appropriate.</p><p>Model availability, speed, accuracy, and capabilities depend on your device, operating system, available memory and storage, model version, and app version. Internet access may be required for installation, updates, and model downloads; core inference is intended to work offline after setup.</p></> },
  { id: "ai-output", title: "AI output and accuracy", content: <><p className="sa-legal-note"><strong>AI-generated responses may be incomplete, outdated, inaccurate, or inappropriate.</strong> Always review important output and verify facts using reliable sources.</p><p>Subra AI is not a substitute for professional medical, legal, financial, mental-health, safety, or other specialist advice. Do not rely on the app for emergencies, diagnoses, treatment decisions, legal deadlines, financial transactions, or decisions where an error could cause harm.</p></> },
  { id: "use", title: "Responsible and prohibited use", content: <><p>You may use Subra AI only for lawful purposes and in accordance with these Terms and applicable third-party conditions. You must not use the app to:</p><ul><li>violate law or another person&apos;s intellectual-property, privacy, publicity, confidentiality, or other rights;</li><li>create or facilitate child sexual abuse or exploitation, non-consensual intimate content, human trafficking, harassment, hate, violence, self-harm, fraud, impersonation, deceptive practices, or other harmful or illegal activity;</li><li>generate malware, credentials, instructions for unauthorized access, or content intended to compromise security;</li><li>make high-impact decisions about another person in employment, housing, credit, insurance, education, healthcare, legal services, or access to essential services;</li><li>perform biometric identification, unlawful surveillance, or process another person&apos;s image without any consent or legal basis that is required;</li><li>present AI output as verified professional advice or human-authored content where disclosure is required; or</li><li>reverse engineer, export, copy, or redistribute protected components except as applicable law and the relevant licence expressly permit.</li></ul><p>Do not use Subra AI for emergencies or where an error or delay could cause death, personal injury, financial loss, legal harm, or damage to property. Contact qualified professionals or emergency services when appropriate.</p></> },
  { id: "content", title: "Your content and generated output", content: <><p>You are responsible for prompts, images, and other material you provide and for your use and disclosure of generated output. You represent that you have all rights, permissions, and lawful bases necessary to use that material. The current version processes the active conversation on your device and does not maintain a Subra AI server-side chat record.</p><p>Subra AI does not claim ownership of your prompts. Subject to applicable law and third-party rights, you may use generated output at your own risk. Output may not be unique, may resemble content produced for others, may be subject to third-party rights, and may not qualify for intellectual-property protection. We do not guarantee ownership, exclusivity, or non-infringement.</p></> },
  { id: "third-party", title: "Third-party technology and terms", content: <><p>The app includes or relies on third-party technology and distribution services, including Google LiteRT/LiteRT-LM, Gemma, Hugging Face, platform app stores, and potentially Google ML Kit in a future version. Separate licences, acceptable-use rules, privacy policies, export restrictions, and notices may apply.</p><p>Your use of Gemma-powered functionality must comply with the <a href="https://ai.google.dev/gemma/terms" target="_blank" rel="noreferrer">Gemma Terms of Use</a> and <a href="https://ai.google.dev/gemma/prohibited_use_policy" target="_blank" rel="noreferrer">Gemma Prohibited Use Policy</a>. You may not export or redistribute a model unless its applicable terms permit it and you provide every required notice. Google, ML Kit, LiteRT, Gemma, Hugging Face, Apple, and related marks belong to their respective owners; their inclusion does not imply endorsement.</p></> },
  { id: "updates", title: "Updates and availability", content: <><p>We may add, change, suspend, or discontinue features, model versions, or device support. We do not guarantee that the app will always be available, error-free, compatible with every device, or capable of producing a response to every prompt.</p></> },
  { id: "ip", title: "Intellectual property", content: <><p>Subra AI&apos;s app interface, branding, original code, and documentation are protected by applicable intellectual-property laws. These terms grant you a limited, revocable, non-exclusive, non-transferable license to use the app for its intended purpose. They do not transfer ownership of the app or third-party components.</p></> },
  { id: "disclaimers", title: "Disclaimers and limitation of liability", content: <><p>To the maximum extent permitted by law, the app, models, and output are provided “as is” and “as available,” without express or implied warranties of accuracy, reliability, availability, merchantability, fitness for a particular purpose, title, or non-infringement. We do not promise that the app will be uninterrupted, secure, error-free, or suitable for your intended use.</p><p>To the maximum extent permitted by law, the Developer will not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages, loss of data, profits, opportunity, or goodwill, or harm resulting from use of or inability to use the app or reliance on its output. Nothing in these Terms limits liability or mandatory consumer rights that applicable law does not permit us to limit.</p></> },
  { id: "indemnity", title: "Your responsibility to us", content: <><p>To the extent permitted by applicable law, you will be responsible for claims, losses, and reasonable costs arising from your unlawful use of Subra AI, material breach of these Terms, or infringement of another person&apos;s rights. This provision does not apply to the extent a claim results from the Developer&apos;s own unlawful conduct and does not reduce non-waivable consumer protections.</p></> },
  { id: "termination", title: "Termination", content: <><p>You may stop using Subra AI at any time by uninstalling it. We may restrict access to future versions or services if you materially violate these terms, subject to applicable law. Provisions that by their nature should survive termination—including disclaimers, liability limits, and intellectual-property provisions—will survive.</p></> },
  { id: "app-stores", title: "App-store terms", content: <><p>If you obtain Subra AI through Apple&apos;s App Store, Apple&apos;s Standard Licensed Application End User License Agreement applies to the extent applicable, and these Terms supplement it. Apple is not responsible for providing maintenance or support for Subra AI except as required by law, and Apple and its subsidiaries are third-party beneficiaries of these Terms as they relate to the licensed app.</p><p>Your use must also comply with the usage rules and other terms of the store through which you obtained the app. If these Terms conflict with mandatory app-store terms, the mandatory terms control to the extent of the conflict.</p></> },
  { id: "law", title: "Governing law, changes, and general terms", content: <><p>These Terms are governed by the laws of India. Subject to mandatory consumer-law rights and any forum that applicable law requires, courts located in Bengaluru, Karnataka, India will have jurisdiction over disputes relating to these Terms or Subra AI.</p><p>We may update these Terms when the app, technology, or legal requirements change. Material changes will be communicated through the app or website when appropriate. Continuing to use the app after revised Terms take effect constitutes acceptance where permitted by law.</p><p>If a provision is unenforceable, the remaining provisions remain effective. A failure to enforce a provision is not a waiver. These Terms, the Privacy Policy, applicable app-store terms, and incorporated third-party terms constitute the agreement governing your use of Subra AI. Mandatory consumer rights remain unaffected.</p></> },
];

export default function TermsPage() { return <LegalPage eyebrow="Use Subra AI responsibly" title="Terms of Use" intro="These terms explain what you can expect from an offline AI assistant—and what Subra AI expects from you." sections={sections} />; }
