import type { Metadata } from "next";
import LegalPage, { type LegalSection } from "../LegalPage";

export const metadata: Metadata = {
  title: "Terms of Use | Subra AI",
  description: "Terms governing use of the Subra AI offline, on-device AI chat application.",
  alternates: { canonical: "/subra-ai/terms" },
  openGraph: { title: "Terms of Use | Subra AI", description: "Terms for using the Subra AI offline chat app.", url: "/subra-ai/terms", type: "website" },
};

const sections: LegalSection[] = [
  { id: "acceptance", title: "Acceptance of these terms", content: <><p>These Terms of Use form an agreement between you and the developer of Subra AI. By downloading, installing, or using the app, you agree to these terms and the Subra AI Privacy Policy. If you do not agree, do not use the app.</p></> },
  { id: "service", title: "What Subra AI provides", content: <><p>Subra AI provides a general-purpose chat interface powered by an on-device language model using Google ML Kit and Gemma 4. Model availability, speed, and capabilities depend on your device, operating system, available storage, and app version.</p><p>An internet connection may be required for installation, updates, and model downloads, although the core inference experience is intended to work offline after setup.</p></> },
  { id: "ai-output", title: "AI output and accuracy", content: <><p className="sa-legal-note"><strong>AI-generated responses may be incomplete, outdated, inaccurate, or inappropriate.</strong> Always review important output and verify facts using reliable sources.</p><p>Subra AI is not a substitute for professional medical, legal, financial, mental-health, safety, or other specialist advice. Do not rely on the app for emergencies, diagnoses, treatment decisions, legal deadlines, financial transactions, or decisions where an error could cause harm.</p></> },
  { id: "use", title: "Responsible use", content: <><p>You may use Subra AI for lawful, personal purposes. You must not use the app to:</p><ul><li>violate applicable laws or another person&apos;s rights;</li><li>create, facilitate, or distribute harmful, abusive, exploitative, or fraudulent content;</li><li>develop malware, bypass security, or gain unauthorized access to devices or systems;</li><li>misrepresent AI output as verified professional advice or as a human-authored statement where disclosure is required; or</li><li>reverse engineer or redistribute protected components except where applicable law or their licenses expressly permits it.</li></ul></> },
  { id: "content", title: "Your content and local data", content: <><p>You are responsible for the prompts and other material you enter and for how you use generated output. Do not enter content you do not have the right to use. Because chats are stored locally, you are responsible for securing your device and managing or deleting your conversation history.</p><p>Subra AI does not claim ownership of the prompts you enter. Subject to applicable law and third-party rights, you may use generated output at your own risk.</p></> },
  { id: "third-party", title: "Third-party technology", content: <><p>The app includes or relies on third-party technology, including Google ML Kit and Gemma. Those components may be governed by separate licenses, acceptable-use terms, and notices. Google, ML Kit, Gemma, and related marks belong to their respective owners. Their inclusion does not imply endorsement of Subra AI.</p></> },
  { id: "updates", title: "Updates and availability", content: <><p>We may add, change, suspend, or discontinue features, model versions, or device support. We do not guarantee that the app will always be available, error-free, compatible with every device, or capable of producing a response to every prompt.</p></> },
  { id: "ip", title: "Intellectual property", content: <><p>Subra AI&apos;s app interface, branding, original code, and documentation are protected by applicable intellectual-property laws. These terms grant you a limited, revocable, non-exclusive, non-transferable license to use the app for its intended purpose. They do not transfer ownership of the app or third-party components.</p></> },
  { id: "disclaimers", title: "Disclaimers and liability", content: <><p>To the maximum extent permitted by law, the app is provided “as is” and “as available,” without warranties of accuracy, fitness for a particular purpose, non-infringement, or uninterrupted operation.</p><p>To the maximum extent permitted by law, the developer will not be liable for indirect, incidental, special, consequential, or punitive damages, loss of data, lost profits, or harm resulting from your use of or reliance on the app or its output. Nothing in these terms excludes liability that cannot legally be excluded.</p></> },
  { id: "termination", title: "Termination", content: <><p>You may stop using Subra AI at any time by uninstalling it. We may restrict access to future versions or services if you materially violate these terms, subject to applicable law. Provisions that by their nature should survive termination—including disclaimers, liability limits, and intellectual-property provisions—will survive.</p></> },
  { id: "law", title: "Governing terms and changes", content: <><p>Applicable mandatory consumer laws remain unaffected. We may update these terms as the app or legal requirements change. Continuing to use the app after revised terms take effect means you accept them, where permitted by law.</p></> },
];

export default function TermsPage() { return <LegalPage eyebrow="Use Subra AI responsibly" title="Terms of Use" intro="These terms explain what you can expect from an offline AI assistant—and what Subra AI expects from you." sections={sections} />; }
