import type { Metadata } from "next";
import LegalPage, { type LegalSection } from "../LegalPage";

export const metadata: Metadata = {
  title: "Privacy Policy | Subra AI",
  description: "Learn how Subra AI handles prompts, images, model downloads, and on-device AI processing.",
  alternates: { canonical: "/subra-ai/privacy-policy" },
  openGraph: { title: "Privacy Policy | Subra AI", description: "Privacy details for the Subra AI offline chat app.", url: "/subra-ai/privacy-policy", type: "website" },
};

const sections: LegalSection[] = [
  { id: "overview", title: "Privacy at a glance", content: <><p className="sa-legal-note"><strong>Subra AI is designed as an offline, on-device AI app.</strong> Prompts, selected images, and generated responses are processed on your device and are not sent to or stored by a Subra AI server for inference.</p><p>The app does not require an account, sell your chat content, use it for advertising, or use it to train a remote model. Limited network connections are used for app and model downloads as described below.</p></> },
  { id: "information", title: "Information you provide", content: <><p>You may enter prompts and choose images from your camera or photo library. The current version holds prompts, selected images, and generated responses temporarily while the conversation is open; it does not provide a persistent Subra AI conversation-history account or server-side chat record.</p><p>Subra AI does not ask for your name, email address, or phone number to use its core features. Please do not enter personal information or material that you do not have the right or permission to process.</p></> },
  { id: "inference", title: "On-device AI processing", content: <><p>The current version uses a <strong>Gemma 4</strong> model through Google <strong>LiteRT/LiteRT-LM</strong> technology to perform inference on your device. A future app version may use <strong>Google ML Kit</strong> or other on-device components; this policy and the applicable store disclosures will be updated before their data practices materially change.</p><ul><li>Prompts and selected images are provided to the locally running model.</li><li>Generated responses are produced locally.</li><li>Chat content is not uploaded to a Subra AI cloud service for inference.</li><li>Chat content is not sold, used for advertising, or used by Subra AI to train a remote model.</li></ul></> },
  { id: "connections", title: "Downloads and network connections", content: <><p>An internet connection is required to obtain the app and its updates and may be required to download ML components or model files. The current version downloads the Gemma model from <a href="https://huggingface.co/privacy" target="_blank" rel="noreferrer">Hugging Face</a>. App stores, operating-system providers, Google, Hugging Face, internet providers, or other distribution providers may receive ordinary connection information such as your IP address, device or client information, request time, requested file, and download status.</p><p>Those independent providers process information under their own terms and privacy policies. Subra AI does not receive their server logs. After the required model is available, core inference is intended to work offline.</p></> },
  { id: "storage", title: "Storage, deletion, and retention", content: <><p>The current version does not preserve a chat-history library after the active conversation ends. Prompts and responses may remain temporarily in app memory while the conversation is open and are cleared when the app process or conversation is reset. Images you take or choose remain subject to your device&apos;s photo-library and temporary-file behavior.</p><p>Downloaded model files remain on your device until you delete them using the app&apos;s model-management controls, clear the app&apos;s data, or uninstall the app. If you choose to export a model file, that copy remains in shared device storage until you delete it. Operating-system backups may include eligible app data according to your platform and backup settings.</p></> },
  { id: "permissions", title: "Camera and photo permissions", content: <><p>If you choose to take or select an image, Subra AI requests camera or photo-library access and provides the selected image to the on-device model for analysis. Subra AI does not upload that image to a Subra AI server. You can deny or revoke permission in system settings; doing so disables the related image feature.</p><p>The exact permission interface and the scope of photo access may vary by platform, operating-system version, and app version.</p></> },
  { id: "third-parties", title: "Third-party services", content: <><p>Subra AI relies on platform app stores, operating-system services, Google AI technology, and Hugging Face model distribution. These parties may process data independently when you use their services. Their inclusion does not mean they sponsor or endorse Subra AI.</p><p>The current version does not include advertising or cross-app tracking. If analytics, crash reporting, cloud inference, accounts, or other data-collection features are introduced, this policy and store privacy disclosures will be updated before release.</p></> },
  { id: "security", title: "Security", content: <><p>Local processing reduces network exposure but no device or software is completely secure. Protect your device with a passcode and current security updates. Anyone with access to your unlocked device may be able to view the active conversation, selected images, downloaded models, or exported files.</p></> },
  { id: "children", title: "Children's privacy", content: <><p>Subra AI is not directed to children under 13, or the minimum digital-consent age in their country. We do not knowingly collect personal information from children through an account or cloud chat service.</p></> },
  { id: "rights", title: "Your choices and rights", content: <><p>Because Subra AI does not maintain a user account or server-side conversation record, we generally cannot retrieve, correct, or delete a conversation from our servers. You control the active conversation and local files through the app and device, and you can remove app data by clearing it or uninstalling the app.</p><p>Depending on where you live, applicable law may provide additional rights. To ask a privacy question or exercise an applicable right concerning data controlled by the Subra AI developer, contact the address below. We may need enough information to understand and verify your request.</p></> },
  { id: "changes", title: "Changes to this policy", content: <><p>We may update this policy when the app, its technology, or legal requirements change. The updated date will appear at the top of this page. Material changes will be communicated through the app or website when appropriate.</p></> },
];

export default function PrivacyPolicyPage() { return <LegalPage eyebrow="Local-first privacy" title="Privacy Policy" intro="Subra AI is built so that your questions and the model's answers can stay on the device in front of you." sections={sections} />; }
