import type { Metadata } from "next";
import LegalPage, { type LegalSection } from "../LegalPage";

export const metadata: Metadata = {
  title: "Privacy Policy | Subra AI",
  description: "Learn how Subra AI protects your privacy through offline, on-device AI inference and local conversation storage.",
  alternates: { canonical: "/subra-ai/privacy-policy" },
  openGraph: { title: "Privacy Policy | Subra AI", description: "Privacy details for the Subra AI offline chat app.", url: "/subra-ai/privacy-policy", type: "website" },
};

const sections: LegalSection[] = [
  { id: "overview", title: "Privacy at a glance", content: <><p className="sa-legal-note"><strong>Subra AI is designed as an offline, on-device chat app.</strong> The content of your chats is processed locally and is not sent to, stored by, or used to train models on a Subra AI server.</p><p>This policy explains what happens to information when you use Subra AI and describes limited situations in which your device may connect to third-party services.</p></> },
  { id: "information", title: "Information you create", content: <><p>When you use the app, you may create prompts, generated responses, chat titles, preferences, and other conversation data. This information is stored locally on your device so the app can provide and preserve your chat experience.</p><p>Subra AI does not require you to create an account and does not ask for your name, email address, or phone number to use the core chat features.</p></> },
  { id: "inference", title: "On-device AI processing", content: <><p>Subra AI uses <strong>Google ML Kit</strong> and a <strong>Gemma 4</strong> model to perform language-model inference on your device. Prompts are provided to the locally running model, and responses are generated locally.</p><ul><li>Chat content is not uploaded to a Subra AI cloud service for inference.</li><li>Chat content is not sold or used by Subra AI for advertising.</li><li>Chat content is not used by Subra AI to train a remote model.</li></ul></> },
  { id: "connections", title: "Downloads and network connections", content: <><p>An internet connection may be required to download Subra AI, app updates, ML components, or model files. When a download is made, the app store, operating-system provider, Google, or a distribution provider may receive standard technical information such as your IP address, device type, request time, and download status.</p><p>Those providers process information under their own privacy policies. After the required model is available, the core chat and inference experience is intended to work offline.</p></> },
  { id: "storage", title: "Storage, deletion, and retention", content: <><p>Conversation history and app preferences remain on your device until you delete them, clear the app&apos;s data, or uninstall the app. You can delete individual chats or local history using the controls provided in the app.</p><p>Device backups managed by your operating system may include app data depending on your device settings. Those backups are controlled by you and your platform provider, not by a Subra AI account service.</p></> },
  { id: "permissions", title: "Device permissions", content: <><p>Subra AI requests only permissions needed for features you choose to use. The exact permissions shown by your device may vary by platform and app version. You can review or revoke permissions in system settings; doing so may disable the related feature.</p></> },
  { id: "security", title: "Security", content: <><p>Local processing reduces the amount of chat data exposed to networks, but no device or software is completely secure. Protect your device with a passcode and current security updates. Anyone with access to your unlocked device may be able to view locally stored chats.</p></> },
  { id: "children", title: "Children's privacy", content: <><p>Subra AI is not directed to children under 13, or the minimum digital-consent age in their country. We do not knowingly collect personal information from children through an account or cloud chat service.</p></> },
  { id: "rights", title: "Your choices and rights", content: <><p>Because Subra AI does not maintain a user account or server-side conversation record, the most direct way to access, correct, export (where supported), or delete chat information is through the app and your device. Depending on where you live, applicable law may provide additional privacy rights.</p></> },
  { id: "changes", title: "Changes to this policy", content: <><p>We may update this policy when the app, its technology, or legal requirements change. The updated date will appear at the top of this page. Material changes will be communicated through the app or website when appropriate.</p></> },
];

export default function PrivacyPolicyPage() { return <LegalPage eyebrow="Local-first privacy" title="Privacy Policy" intro="Subra AI is built so that your questions and the model's answers can stay on the device in front of you." sections={sections} />; }
